apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bstage
  description: Backstage Tech Docs
  labels:
    example.com/custom: custom_label_value
  annotations:
   
      bitrise.io/app: 'react-native'
      sentry.io: 'node-work'
  tags:
    - java
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: public-websites

